/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistema.view;

/**
 *
 * @author mashi
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuBar = new javax.swing.JMenuBar();
        CadMenu = new javax.swing.JMenu();
        UsuarioCadMenu = new javax.swing.JMenuItem();
        ModulosCadMenu = new javax.swing.JMenuItem();
        QuizzCadMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PAC-AdminMenu");

        CadMenu.setText("Cadastros");

        UsuarioCadMenu.setText("Usuarios");
        UsuarioCadMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioCadMenuActionPerformed(evt);
            }
        });
        CadMenu.add(UsuarioCadMenu);

        ModulosCadMenu.setText("Modulos");
        ModulosCadMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModulosCadMenuActionPerformed(evt);
            }
        });
        CadMenu.add(ModulosCadMenu);

        QuizzCadMenu.setText("Quizzes");
        CadMenu.add(QuizzCadMenu);

        MenuBar.add(CadMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioCadMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioCadMenuActionPerformed
        FrmUsuario frmUsuario = new FrmUsuario();
        frmUsuario.setVisible(true);
    }//GEN-LAST:event_UsuarioCadMenuActionPerformed

    private void ModulosCadMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModulosCadMenuActionPerformed
        FrmModulo frmModulo = new FrmModulo();
        frmModulo.setVisible(true);
    }//GEN-LAST:event_ModulosCadMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu CadMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem ModulosCadMenu;
    private javax.swing.JMenuItem QuizzCadMenu;
    private javax.swing.JMenuItem UsuarioCadMenu;
    // End of variables declaration//GEN-END:variables
}
