/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistema.view;

import br.com.sistema.dao.ModuloDAO;
import br.com.sistema.model.Modulo;
import javax.swing.JOptionPane;

/**
 *
 * @author mashi
 */
public class PnlModulo extends javax.swing.JPanel {

    public int idUpdate;
    /**
     * Creates new form PnlModulo
     */
    public PnlModulo() {
        initComponents();
        ConteudoTxt.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloTxt = new javax.swing.JTextField();
        TituloLb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ConteudoTxt = new javax.swing.JTextArea();
        ConteudoLb = new javax.swing.JLabel();
        CadBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        CancelarBtn = new javax.swing.JButton();

        TituloTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        TituloLb.setText("Titulo:");

        ConteudoTxt.setColumns(20);
        ConteudoTxt.setRows(5);
        jScrollPane1.setViewportView(ConteudoTxt);

        ConteudoLb.setText("Conteudo:");

        CadBtn.setText("Cadastrar");
        CadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadBtnActionPerformed(evt);
            }
        });

        SaveBtn.setText("Salvar");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        CancelarBtn.setText("Cancelar");
        CancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(CadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TituloLb)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TituloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(ConteudoLb))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TituloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TituloLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConteudoLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadBtn)
                    .addComponent(SaveBtn)
                    .addComponent(CancelarBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBtnActionPerformed
        FrmModulo.painel.setVisible(false);
    }//GEN-LAST:event_CancelarBtnActionPerformed

    private void CadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadBtnActionPerformed
        cadastrar();
    }//GEN-LAST:event_CadBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        salvar();
    }//GEN-LAST:event_SaveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton CadBtn;
    private javax.swing.JButton CancelarBtn;
    private javax.swing.JLabel ConteudoLb;
    public javax.swing.JTextArea ConteudoTxt;
    public javax.swing.JButton SaveBtn;
    private javax.swing.JLabel TituloLb;
    public javax.swing.JTextField TituloTxt;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void cadastrar() {
        Modulo modulo = new Modulo();
        modulo.setTitulo(TituloTxt.getText());
        modulo.setConteudo(ConteudoTxt.getText());
        ModuloDAO.salvar(modulo);
        JOptionPane.showMessageDialog(this, "Modulo cadastrado com sucesso!");
        limparCampos();
        FrmModulo.painel.setVisible(false);
        FrmModulo.listarModulos();
    }

    private void salvar() {
        Modulo modulo = new Modulo();
        modulo.setId(idUpdate);
        modulo.setTitulo(TituloTxt.getText());
        modulo.setConteudo(ConteudoTxt.getText());
        ModuloDAO.salvar(modulo);
        JOptionPane.showMessageDialog(this, "Modulo cadastrado com sucesso!");
        limparCampos();
        FrmModulo.painel.setVisible(false);
    }

    private void limparCampos() {
        TituloTxt.setText("");
        ConteudoTxt.setText("");
    }
}
